### ISSUE TITLE
Documentation Webpage returning 404 from Github Pages

### ISSUE THREAD

**Issue by Skeegan123** [spacedentist/spr#200]
When navigating to the SPR docs from the link in the README you receive a 404 error from Github Pages. A screenshot is attached below.
<img width="1512" alt="Screenshot 2024-06-25 at 9 56 41 AM" src="https://github.com/spacedentist/spr/assets/41558005/3f8e96e4-041a-46fc-aea5-0b5f898f8483">

**Comment by jdai8** [comment]
It looks like the new documentation is here: https://spacedentist.github.io/spr/

**Comment by spacedentist** [comment]
Fixed by #204
